certRoller {
  caName = "MyNebulaCA"
  pubDir = "pubs"

  hosts = {
    "host1": {
      name: "host1.example.com",
      networks: ["192.168.1.10/24"],
      groups: ["default-group"]
      # Optional: A list of CIDR routes to embed in the certificate.
      # Corresponds to the -unsafe-routes flag in `nebula-cert sign`.
      # unsafeNetworks: ["10.0.0.0/8", "172.16.0.0/12"]
    },
    "host2": {
      name: "host2.example.com",
      networks: ["192.168.1.11/24"],
      groups: ["default-group", "backup-server"]
    }
  }
}

configServer {
  host = "0.0.0.0"
  port = 8080
  templatesDir = "common/src/main/resources"
  pkiKeyPath = "/etc/nebula/host.key"
  configDir = "."
  privilegedIps = []
  numConfigs = 11
}
