cert-roller {
  caName = "MyNebulaCA"
  pubDir = "pubs"

  hosts = {
    "host1": {
      name: "host1.example.com",
      ip: "192.168.1.10/24",
      groups: ["default-group"]
    },
    "host2": {
      name: "host2.example.com",
      ip: "192.168.1.11/24",
      groups: ["default-group", "backup-server"]
    }
  }
}

config-server {
  host = "0.0.0.0"
  port = 8080
  templatePath = "src/main/resources/template.yaml"
  pkiKeyPath = "/etc/nebula/host.key"
  configDir = "."
  labServerInboundGroups = ["default-group"]
  privileged-ips = []
  num-configs = 5
}
